language: python
cache: pip
python:
- '3.7'
install:
- pip install awscli
- pip install aws-sam-cli
jobs:
  include:
  - stage: test
    script:
    - pip install pytest
    - pip install -e .
    - pytest . -v
  - stage: deploy
    script:
    - sam validate
    - sam build --debug
    - sam package --s3-bucket manageme-travis-deployment-bucket  --output-template-file
      out.yml --region eu-west-1
    - sam deploy --template-file out.yml --stack-name manageme-stack --region eu-west-1
      --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
    skip_cleanup: true
    if: branch = master
notifications:
  email:
    on_failure: always
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - secure: fEV14TKev+UCh4Pusz8HUwtQyG8GkUogG6+3evt6Mkv1y39FDW796zZPtURHbsHBUkS+PH1adBGVWZwK1Nh6U3NRzHsRYhWeR4O8mbIEoKTDO863xvmBx68kmwuRKwgmtbeWShzVgBfevs5mYCBppOzz1eYzHvSy/qtrPJZwWlP7MFj5ImOadNvLiCkuwk06u02ywKhawixxauxSD8f7T5im/7cRRhNXKphd7OAce0qjFIe9IsIoP+fd040B1d0POMUeE1ACmCkf95iOPRKdbM8VvXd73V1RfgrRRG+VwMqueeGIkBGjof1caSn+2Fw0UfdvzUcD8osDy7dYc823q8pKShBx1QFIO5hqOpS4vVlrUGIW1cQiE+fFkC8in3Yge1JNEXY0ZgPLPA6TzEkpunWqEgLfH638X2w4u9cQOX0rSAVe9ngg32EX4YXkvqXwh+F0SVwN0LU0eTUKRdb5flOOnkOwvUXtEipL18Vzhms/6ZiWHHFOioLjA2BwcA8wT1vinew0dWVXIu86r6JvjUZd34+aCP9C3SgjQKgm7g+6HJNvf/EFJAzBRJidQoDJYVlWcH9ItwxFQNLV92px8qVgSwvzgVix4OSScwzeTR0Hb9dkr6TQZvrLZGOArgzK/gmjosvVEeXxVeVovYVXPeydskD5ynF0j2zzyG2uUls=
  - secure: xx9qiwF1+gPrFj1chiL1PZ5hltvbKiKTopqxAW8GDrd6nEX7nL65+fr0SVpO0/vBXxQP0DovysZpyxVmhASn/GdrCagaqsGbnIKdg0bgpAL0MPtkGCZ2qne8uxIKf9qu1cy9SlIv9JTFfxXVJagkJx39RXEn3YasVPw0ouzmHLFoUi95gdbh/k3VSqiKbGta5g4N9BE58F/Piu0cFCLJhKYPeJkulG50IdaAWa7EqxYEdWp8h2timEGoI/N4QV5L+KwRguDziIemnBXL2Yemmx1sc2PONyTjcXdxTRE4/cVJpUQPWOoi87iGtGK22b33Cm12YpE4IJPiHu9ejwU37McB6wm/Y1PW2uV80CkANdQlt9nTrqNp+yVLlZNmaml634UMoJLRJSjMW29enXimrZKYzG+wN+yRRiSFgeBJnwwlN3upx4We+EE2lWHBvJzEh5LggQBbZPMhij8lN53jR3JzWwL1M1uMv79uMIt2tVo9sYhOTPq1z70LBDzvtiU4kFT91qFKuNEEZ4XnbMLcw/JDPbm2Hu6c5TmRemArbmfRIulsM8qZewLKrJXhWxjWDKrGz0UZWE0PkqVRdNCPUZfkiZvgEfHGTI4jv8jAjyd9v+8IuHtTD4SyPJjYVTdivNcQPg1xlR4tiN2vS0JZup/ZwQp0nXzxHMPXIsqYsm4=
