language: python
cache: pip
python:
- '3.7'
install:
- pip install awscli
- pip install aws-sam-cli
jobs:
  include:
  - stage: test
    script:
    - pip install pytest
    - pip install -e .
    - pytest . -v
  - stage: deploy
    script:
    - sam validate
    - sam build --debug
    - sam package --s3-bucket manageme-travis-deployment-bucket  --output-template-file
      out.yml --region eu-west-1
    - sam deploy --template-file out.yml --stack-name manageme-stack --region eu-west-1
      --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
    skip_cleanup: true
    if: branch = master
notifications:
  email:
    on_failure: always
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - secure: 1kfNFhQES5hbPVEDY5/zANRM8B61XzF7Kuw0PS792UWTjlSPPST+UouwD9U5EuQ+syKi5JATeu7s0E8rFCXjEpVUYb0WuBJ/+K3dqlTPFGbZy/OcNjuLM17J3O1bp4qAOKSGwT/H1bq4T6iGKPVjBKc7ASoPcCpyjxmvVDlzjaxmLmXLnKY3lgK8SJbvcnWWRVvObTCgrzRrFJB/VnmrJlIApHTsaDzIQx2n3rNHrF0wXm8Ms8HQCUeHCnbM8U5ao4UU+Ay/2r2cm4QUaUZ7pRFDXhw1PrcEVih1MKkPsgoDY4jkmwxy/TCGp+CVajZS/f9O+ECiYpZqBZmj/3u7JGz6dG8iiNWkjR9/wQE3dUetKr1G4YUIyBVoJTCr1OSSel/53bNUl5bVBl2wNdsBKVgLavthWB8rAmE52F1iAJ4QnEQBu+BeJ2JYj57SyD8eqhfNZQOytb7RuO0AoHAzicz+ILORO246o9Yn11Rl4Zu94yFo5s6MGD6p4YmnPQxUmQLnfQhprK+N2QX3FiUZiTV0BAIyzNOPc7eIYMM17DJCSncyVPjYUSsShI13ypAl3gP0toujoBdbSWiDAu+6CBTc+N4MzAu/iuUskQao2fw4f4mm6k67IdXUw5Adfh1O0DvNHyhufaMH60RhkQGJfEskHcAxhZ6IH/kdU/WqKps=
  - secure: Akp/kNaOqes670hYqRNuWCbp1zHeujSEDtQil+C0jF6nWaSluoNW0PjxS9PLcQytti0dBiqoxgccbRcRSLuGYAqZ2NolLLTojp5IEHtb6U3AHw48SS8Q28dIFAmVRSS0yndSsAlXfXygUTqypKQWwtmaNHYCRirazEVluH1JrIkhG85yH+CfR32SR6Ekosp4CJuNffw7luBORJb9wQe2cQQXBA7+Zfrt6boChGcMFj2TuXvMc6ycdysZQKYmwYMFezY4vcvLTc0++lObEGmLyohYmGrFoyITjyvhyj0OIfhW/Ot84zAl0mePwUhkcRBqVJ1CyCQVchgN5mgPcl2NVjDQi/Y4CYU1xJob3mwljRUadyiSXjYbJXBzd9SAsIkqLmvCA6hgRMnx9ZgOHjdmu42WtBeZr1LD2tWsILQzfRAp8/+nPXNjlwdRIu9weadRQ/5+sCCatZJcPTZz2KD+hiBHrMDM/JnVKikI6ZOpWyX1LhiGwUz/NenqKMlenDWG5r2CRKj7ZoMBynZNy9e5ohh5uytFyCDZv3gY4AsBNzhVC408ViwmxzT4TXVIdpTaK+fINJn/2zKW7Ox9Q8pp/ZrH92NZlmj53RDmrbUPGyIkdAMQ7iFpJznJ6vnedXp6tH995ZkX5FAqy5rL4FmNdBaJvxyKUEiTIwLQxvNMT2I=
